# Generated by Django 3.2.20 on 2023-10-03 11:30

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plate', models.CharField(max_length=8, unique=True, validators=[django.core.validators.RegexValidator('[A-Z]{3}[-][0-9][0-9A-J][0-9]{2}', message='Wrong Format')])),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('paid', models.BooleanField(default=False)),
                ('left', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Historico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('checkIn', models.DateTimeField()),
                ('checkOut', models.DateTimeField()),
                ('id_reservation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parking.reservation')),
            ],
        ),
    ]
