# Generated by Django 3.2.20 on 2023-08-29 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plate', models.CharField(max_length=8)),
                ('timeOut', models.TimeField(verbose_name='Time started')),
                ('pay', models.BooleanField()),
            ],
        ),
    ]
