# Generated by Django 3.2.20 on 2023-10-03 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historico',
            name='checkOut',
            field=models.DateTimeField(null=True),
        ),
    ]
