# Generated by Django 3.2.20 on 2023-09-14 12:51

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0002_auto_20230904_1033'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='left',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='plate',
            field=models.CharField(max_length=8, unique=True, validators=[django.core.validators.RegexValidator('[A-Z]{3}[-][0-9][0-9A-J][0-9]{2}', message='Wrong Format')]),
        ),
    ]
