# Generated by Django 3.2.20 on 2023-09-15 11:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0003_auto_20230914_0951'),
    ]

    operations = [
        migrations.CreateModel(
            name='Historico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('time', models.DurationField()),
                ('id_reservation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parking.reservation')),
            ],
        ),
    ]
