# Generated by Django 3.2.20 on 2023-09-05 11:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0003_alter_reservation_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='plate',
            field=models.CharField(max_length=8, unique=True, validators=[django.core.validators.RegexValidator('[A-Z]{3}[-][0-9][0-9A-J][0-9]{2}', message='Wrong Format')]),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='time',
            field=models.TimeField(auto_now_add=True),
        ),
    ]
