# Generated by Django 3.2.20 on 2023-09-05 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0004_auto_20230905_0828'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='left',
            field=models.BooleanField(default=False),
        ),
    ]
