# Generated by Django 3.2.20 on 2023-10-09 13:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0004_historico_duration'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historico',
            name='duration',
        ),
    ]
